#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# Fish config
rm -rf $HOME/.config/fish/config.fish
ln -s $DOTFILES/fish/config.fish $HOME/.config/fish/config.fish

rm -rf $HOME/.config/fish/alias.fish
ln -s $DOTFILES/fish/alias.fish $HOME/.config/fish/alias.fish

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.local/bin

# Install script to show in fzf the avaible tmux projects.
rm -rf $HOME/.local/bin/tmux-sessionizer
ln -s $DOTFILES/scripts/tmux-sessionizer $HOME/.local/bin/tmux-sessionizer

# Install script to show in fzf the avaible tmux sessions.
rm -rf $HOME/.local/bin/tmux-windowizer
ln -s $DOTFILES/scripts/tmux-windowizer $HOME/.local/bin/tmux-windowizer

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
