#!/usr/bin/env bash

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    selected=$(tmux list-sessions -F '#{#{session_name}}' |\
        sed '/^$/d' |\
        fzf --ansi --header jump-to-session --height 100% --preview 'tmux capture-pane -pt {1}' --pointer=""
    )
else
    selected=$(tmux list-sessions -F '#{?session_attached,,#{session_name}}' |\
        sed '/^$/d' |\
        fzf --ansi --header jump-to-session --height 100% --preview 'tmux capture-pane -pt {1}' --pointer=""
    )
fi


if [[ -z $selected ]]; then
    exit 0
fi


if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux a -t $selected
else
    tmux switch-client -t $selected
fi

