#!/usr/bin/env bash

# Based on the ThePrimeagen but add tmp folder idea from Jess Archer
# https://github.com/ThePrimeagen/.dotfiles/blob/904580dfbb18be3f22d224be953a3f58ac513c69/bin/.local/scripts/tmux-sessionizer

# Check if developer folder exists.
working_dir="$HOME/developer"
second_dir="$HOME/Herd"
work_dir="$HOME/Work"

if [[ ! -d $working_dir ]]; then
    working_dir="$HOME/Developer"
fi

# Check if folder is passed to open in tmux instead of listing all the options.
if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=$(find "$working_dir" "$second_dir" "$work_dir" -mindepth 1 -maxdepth 1 -type d)
    items+=`echo -e "\n/tmp"`
    selected=$(echo "$items" | fzf -d 30% --cycle --ansi --sort --query="$1" --preview="eza --tree --level=1 -s type {}" --header jump-to-project --pointer="")
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

